WebAPPCoreMvcUI/Controllers/ImageController.cs
using Entities.Concrete;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using WebAPPCoreMvcUI.Models.ProductViewModel;

namespace WebAPPCoreMvcUI.Controllers
{
    public class ImageController : Controller
    {
        private readonly HttpClient _httpClient;
        private string url = "https://localhost:44304/api/";
        private readonly IWebHostEnvironment _hostEnvironment;

        public ImageController(HttpClient httpClient, IWebHostEnvironment hostEnvironment)
        {
            _httpClient = httpClient;
            _hostEnvironment = hostEnvironment;
        }

        [HttpGet]
        public async Task<IActionResult> AddProductImages(Guid id)
        {
            
            var product = await _httpClient.GetFromJsonAsync<Product>(url + "Products/getById?productId=" + id);

            ViewBag.ProductName = product.ProductName;
            ViewBag.ProductId = product.Id;

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddProductImages(ProductAddViewModel productAddViewModel)
        {

            if (ModelState.IsValid)
            {
                if (productAddViewModel.Files != null)
                {                   
                    string folder = "Images/ProductImages/";
                    Image image = new Image();
                    foreach (var item in productAddViewModel.Files)
                    {
                        image.ImageName = item.FileName;
                        image.ProductId=productAddViewModel.ProductId;
                        var Path = await UploadImage(folder, item);
                        image.ImagePath = Path.ToString();
                        await _httpClient.PostAsJsonAsync(url + "Images/Add", image);

                    }
                    
                    return RedirectToAction("GetAllProducts", "Product");
                }

            }
            return View();
        }
        private async Task<string> UploadImage(string folderPath, IFormFile formFile)
        {
            folderPath += Guid.NewGuid().ToString() + "_" + formFile.FileName;
            string serverFolder = Path.Combine(_hostEnvironment.WebRootPath, folderPath);
            await formFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
            return "/" + folderPath;
        }
    }
}

WebAPPCoreMvcUI/Controllers/ProductController.cs
using Entities.Concrete;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using WebAPPCoreMvcUI.CustomFilterAttribute;
using WebAPPCoreMvcUI.Models.ProductViewModel;

namespace WebAPPCoreMvcUI.Controllers
{
    [MyCustomAttribute]
    public class ProductController : Controller
    {
        private readonly HttpClient _httpClient;
        private string url = "https://localhost:44304/api/";
        private readonly IWebHostEnvironment _hostEnvironment;
        public ProductController(HttpClient httpClient, IWebHostEnvironment hostEnvironment)
        {
            _httpClient = httpClient;
            _hostEnvironment = hostEnvironment;
        }

        [HttpGet]
        public async Task<IActionResult> AddProduct()
        {
            //Create New Product 
            var model = new ProductAddViewModel();
            var subCategList = await _httpClient.
               GetFromJsonAsync<List<SubCategory>>(url + "SubCategories/getAll");

            ViewBag.SubCategoriesList = new SelectList(subCategList, "Id", "SubCategoryName");

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddProduct(ProductAddViewModel productAddViewModel)
        {

            if (ModelState.IsValid)
            {
                if (productAddViewModel.Files != null)
                {
                    Product productToAdd = new Product()
                    {

                        ProductName = productAddViewModel.ProductName,
                        Description = productAddViewModel.Description,
                        PurchasePrice = productAddViewModel.PurchasePrice,
                        SalePrice = productAddViewModel.SalePrice,
                        DiscountPrice = productAddViewModel.DiscountPrice,
                        AddedDate = productAddViewModel.AddedDate,
                        UnitsInstock = productAddViewModel.UnitsInstock,
                        SubCategoryId = productAddViewModel.SubCategoryId,
                        IsDeleted = productAddViewModel.IsDeleted

                    };

                    AddRequestHeaderToken();
                    HttpResponseMessage responseMessage = await _httpClient.PostAsJsonAsync(url + "Products/add", productToAdd);
                    if (responseMessage.IsSuccessStatusCode)
                    {
                        return RedirectToAction("GetAllProducts", "Product");
                    }

                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAllProducts()
        {
            AddRequestHeaderToken();
            var products = await _httpClient.GetFromJsonAsync<List<Product>>(url + "Products/getAll");
            return View(products);
        }

        [HttpGet]
        public async Task<IActionResult> ProductsByCategoryId(Guid id)
        {
            AddRequestHeaderToken();

            var productList = await _httpClient.GetFromJsonAsync<List<Product>>(url + "Products/getAllProductsWithImages");
            var prodcts = productList.Where(item => item.SubCategory.CategoryId == id).ToList();

            return View(prodcts);
        }


        [HttpGet]
        public async Task<IActionResult> ProductDetail(Guid id)
        {
            var productList = await _httpClient.GetFromJsonAsync<List<Product>>(url + "Products/getAllProductsWithImages");
            var prodct = productList.Where(item => item.Id == id).FirstOrDefault();
            return View(prodct);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateProduct(Guid id)
        {
            var productToUpdate = await _httpClient.GetFromJsonAsync<Product>(url + "Products/getById?productId=" + id);

            var subCategList = await _httpClient.GetFromJsonAsync<List<SubCategory>>(url + "SubCategories/getAll");

            ViewBag.SubCategoriesList = new SelectList(subCategList, "Id", "SubCategoryName");
            return View(productToUpdate);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProduct(Product product)
        {
            HttpResponseMessage responseMessage = await _httpClient.PostAsJsonAsync<Product>(url + "Products/Update", product);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("GetAllProducts", "Product");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> DeleteProduct(Guid id)
        {
            var productToDelete = await _httpClient.GetFromJsonAsync<Product>(url + "Products/getById?productId=" + id);

            return View(productToDelete);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteProduct(Product product)
        {
            HttpResponseMessage responseMessage = await _httpClient.PostAsJsonAsync<Product>(url + "Products/Delete", product);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("GetAllProducts", "Product");
            }
            return View();
        }

        public void AddRequestHeaderToken()
        {
            var token = Request.Cookies["Token"];
            _httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {token}");
        }

        private async Task<string> UploadImage(string folderPath, IFormFile formFile)
        {
            folderPath += Guid.NewGuid().ToString() + "_" + formFile.FileName;
            string serverFolder = Path.Combine(_hostEnvironment.WebRootPath, folderPath);
            await formFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
            return "/" + folderPath;
        }
    }
}

WebAPPCoreMvcUI/ViewComponents/CategoryAsideViewComponent.cs
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace WebAPPCoreMvcUI.ViewComponents
{
    public class CategoryAsideViewComponent: ViewComponent
    {
        private readonly HttpClient _httpClient;
        private string url = "https://localhost:44304/api/";

        public CategoryAsideViewComponent(HttpClient httpClient)
        {
            _httpClient=httpClient;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _httpClient.
                 GetFromJsonAsync<List<Category>>(url + "Categories/getAll");
            return View(categories);
        }
    }
}

WebAPPCoreMvcUI/Views/Product/AddProduct.cshtml
@model WebAPPCoreMvcUI.Models.ProductViewModel.ProductAddViewModel


<div class="container">
    <h4>ProductAddViewModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <form asp-action="AddProduct" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ProductName" class="control-label"></label>
                    <input asp-for="ProductName" class="form-control" />
                    <span asp-validation-for="ProductName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PurchasePrice" class="control-label"></label>
                    <input asp-for="PurchasePrice" class="form-control" />
                    <span asp-validation-for="PurchasePrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SalePrice" class="control-label"></label>
                    <input asp-for="SalePrice" class="form-control" />
                    <span asp-validation-for="SalePrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DiscountPrice" class="control-label"></label>
                    <input asp-for="DiscountPrice" class="form-control" />
                    <span asp-validation-for="DiscountPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AddedDate" class="control-label"></label>
                    <input asp-for="AddedDate" class="form-control" />
                    <span asp-validation-for="AddedDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UnitsInstock" class="control-label"></label>
                    <input asp-for="UnitsInstock" class="form-control" />
                    <span asp-validation-for="UnitsInstock" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SubCategoryName" class="control-label"></label>
                    @Html.DropDownListFor(m=>m.SubCategoryId,
                          ViewBag.SubCategoriesList as SelectList,"Select Category", new {@class="form-control"})
                </div>
                <div class="form-group">
                    
                    <label asp-for="Files" class="control-label">Images</label>
                   
                    <div class="custom-file">
                        <input asp-for="Files"  class="custom-file-input" id="customFile"/>
                        <label class="custom-file-label" for="customFile">Select Images</label>
                    </div>
                    
                    <span asp-validation-for="Files" class="text-danger"></span>
                </div>
               
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</div>

WebAPPCoreMvcUI/Views/Product/GetAllProducts.cshtml
@model IEnumerable<Entities.Concrete.Product>

<div class="container">
    <p>
    <a asp-action="AddProduct">Create New Product</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PurchasePrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SalePrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiscountPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AddedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnitsInstock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubCategoryId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsDeleted)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PurchasePrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SalePrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiscountPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitsInstock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubCategoryId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>
            <td>
                @Html.ActionLink("Edit", "UpdateProduct", new { id=item.Id }) |
                @Html.ActionLink("Delete", "DeleteProduct", new { id=item.Id })|
                @Html.ActionLink("Add Product Image", "AddProductImages","Image", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>
</div>

WebAPPCoreMvcUI/Views/Product/GetProductsByCategoryId.cshtml
@model IEnumerable<Entities.Concrete.Product>

    <div class="section">
    <div class="container">
        <ul>
             
            @foreach (var item in Model)
            {
                <li>@item.ProductName</li>
            }
        </ul>
    </div>
</div>

WebAPPCoreMvcUI/Views/Product/ProductsByCategoryId.cshtml
@model IEnumerable<Entities.Concrete.Product>
@{
    ViewData["Title"] = "ProductsByCategoryId";
}



<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb-tree">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">All Categories</a></li>
                    <li><a href="#">Accessories</a></li>
                    <li class="active">Headphones (227,490 Results)</li>
                </ul>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /BREADCRUMB -->
<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <!-- ASIDE -->
            <div id="aside" class="col-md-3">
                <div class="aside">
                    <h3 class="aside-title">Categories</h3>
                    <div class="checkbox-filter">
                        @await Component.InvokeAsync("CategoryAside")
                    </div>
                </div>
                <!-- aside Widget -->
                <div class="aside">
                    <h3 class="aside-title">Price</h3>
                    <div class="price-filter">
                        <div id="price-slider"></div>
                        <div class="input-number price-min">
                            <input id="price-min" type="number">
                            <span class="qty-up">+</span>
                            <span class="qty-down">-</span>
                        </div>
                        <span>-</span>
                        <div class="input-number price-max">
                            <input id="price-max" type="number">
                            <span class="qty-up">+</span>
                            <span class="qty-down">-</span>
                        </div>
                    </div>
                </div>
                <!-- /aside Widget -->
                <!-- aside Widget -->
                <div class="aside">
                    <h3 class="aside-title">Brand</h3>
                    <div class="checkbox-filter">
                        <div class="input-checkbox">
                            <input type="checkbox" id="brand-1">
                            <label for="brand-1">
                                <span></span>
                                SAMSUNG
                                <small>(578)</small>
                            </label>
                        </div>
                        <div class="input-checkbox">
                            <input type="checkbox" id="brand-2">
                            <label for="brand-2">
                                <span></span>
                                LG
                                <small>(125)</small>
                            </label>
                        </div>
                        <div class="input-checkbox">
                            <input type="checkbox" id="brand-3">
                            <label for="brand-3">
                                <span></span>
                                SONY
                                <small>(755)</small>
                            </label>
                        </div>
                        <div class="input-checkbox">
                            <input type="checkbox" id="brand-4">
                            <label for="brand-4">
                                <span></span>
                                SAMSUNG
                                <small>(578)</small>
                            </label>
                        </div>
                        <div class="input-checkbox">
                            <input type="checkbox" id="brand-5">
                            <label for="brand-5">
                                <span></span>
                                LG
                                <small>(125)</small>
                            </label>
                        </div>
                        <div class="input-checkbox">
                            <input type="checkbox" id="brand-6">
                            <label for="brand-6">
                                <span></span>
                                SONY
                                <small>(755)</small>
                            </label>
                        </div>
                    </div>
                </div>
                <!-- /aside Widget -->
                <!-- aside Widget -->
                <div class="aside">
                    <h3 class="aside-title">Top selling</h3>
                    <div class="product-widget">
                        <div class="product-img">
                            <img src="~/template/img/product01.png" alt="">
                        </div>
                        <div class="product-body">
                            <p class="product-category">Category</p>
                            <h3 class="product-name"><a href="#">product name goes here</a></h3>
                            <h4 class="product-price">$980.00 <del class="product-old-price">$990.00</del></h4>
                        </div>
                    </div>

                    <div class="product-widget">
                        <div class="product-img">
                            <img src="~/template/img/product02.png" alt="">
                        </div>
                        <div class="product-body">
                            <p class="product-category">Category</p>
                            <h3 class="product-name"><a href="#">product name goes here</a></h3>
                            <h4 class="product-price">$980.00 <del class="product-old-price">$990.00</del></h4>
                        </div>
                    </div>

                    <div class="product-widget">
                        <div class="product-img">
                            <img src="~/template/img/product03.png" alt="">
                        </div>
                        <div class="product-body">
                            <p class="product-category">Category</p>
                            <h3 class="product-name"><a href="#">product name goes here</a></h3>
                            <h4 class="product-price">$980.00 <del class="product-old-price">$990.00</del></h4>
                        </div>
                    </div>
                </div>
                <!-- /aside Widget -->
            </div>
            <!-- /ASIDE -->
            <!-- STORE -->
            <div id="store" class="col-md-9">
                <!-- store top filter -->
                <div class="store-filter clearfix">
                    <div class="store-sort">
                        <label>
                            Sort By:
                            <select class="input-select">
                                <option value="0">Popular</option>
                                <option value="1">Position</option>
                            </select>
                        </label>

                        <label>
                            Show:
                            <select class="input-select">
                                <option value="0">20</option>
                                <option value="1">50</option>
                            </select>
                        </label>
                    </div>
                    <ul class="store-grid">
                        <li class="active"><i class="fa fa-th"></i></li>
                        <li><a href="#"><i class="fa fa-th-list"></i></a></li>
                    </ul>
                </div>
                <!-- /store top filter -->
                <!-- store products -->
                <div class="row">
                    <!-- product -->
                    @foreach (var item in Model)
                    {
                        <div class="col-md-4 col-xs-6">
                            <div class="product">
                                <div class="product-img">
                                    @Html.ActionLink("", "ProductsById", new { id=item.Id })
                                    @if (item.Images.FirstOrDefault() != null)
                                    {
                                        <img src="@item.Images.FirstOrDefault().ImagePath" alt="">
                                    }
                                    else
                                    {
                                        <img src="~/template/img/TaftafStore.png" alt="">
                                    }
                                    @*<img src="~/template/img/product01.png" alt="">*@
                                    <div class="product-label">
                                        <span class="sale">-30%</span>
                                        <span class="new">NEW</span>
                                    </div>
                                </div>
                                <div class="product-body">
                                    <p class="product-category">Category</p>
                                    <h3 class="product-name"><a href="#">@item.ProductName</a></h3>
                                    <h4 class="product-price">$@item.DiscountPrice <del class="product-old-price">@item.SalePrice</del></h4>

                                    <div class="product-rating">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    </div>
                                    <div class="product-btns">
                                        <button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
                                        <button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">add to compare</span></button>
                                        @*<button class="quick-view"<i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>*@
                                        <button class="quick-view">@Html.ActionLink("View", "ProductDetail", new { id=item.Id })</button>
                                    </div>
                                </div>
                                <div class="add-to-cart">
                                    <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
                                </div>
                            </div>
                        </div>

                        @*<div class="clearfix visible-lg visible-md visible-sm visible-xs"></div>*@
                    }
                    <!-- /product -->

                    <div class="clearfix visible-lg visible-md visible-sm visible-xs"></div>

                    <!-- product -->
                    <!-- /store products -->
                    <!-- store bottom filter -->
                    <div class="store-filter clearfix">
                        <span class="store-qty">Showing 20-100 products</span>
                        <ul class="store-pagination">
                            <li class="active">1</li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
                        </ul>
                    </div>
                    <!-- /store bottom filter -->
                </div>
                <!-- /STORE -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /SECTION -->
    <!-- NEWSLETTER -->
    <div id="newsletter" class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="newsletter">
                        <p>Sign Up for the <strong>NEWSLETTER</strong></p>
                        <form>
                            <input class="input" type="email" placeholder="Enter Your Email">
                            <button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
                        </form>
                        <ul class="newsletter-follow">
                            <li>
                                <a href="#"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /NEWSLETTER -->